apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twelvet-server-job
  name: twelvet-server-job
  namespace: twelvet   #一定要写名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: twelvet-server-job
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: twelvet-server-job
    spec:
      imagePullSecrets:
        - name: aliyun-docker-registry  #提前在项目下配置访问docker仓库的账号密码
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/twelvet-server-job:v1.$BUILD_NUMBER
          #         readinessProbe:
          #           httpGet:
          #             path: /actuator/health
          #             port: 8082
          #           timeoutSeconds: 10
          #           failureThreshold: 30
          #           periodSeconds: 5
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8082
              protocol: TCP
#          resources:
#            limits:
#              memory: 1024Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: twelvet-server-job
  name: twelvet-server-job
  namespace: twelvet
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: twelvet-server-job
  sessionAffinity: None
  type: ClusterIP