server:
  # 模块是直接运行的 nacos-console 模块，不是标准的springboot 启动过程无法通过修改 application.yml 里面端口号 实现启动端口变更。
  # 在 twelvet-nacos 启动 Main 方法增加 System.setProperty("server.port","8080");
  port: 8848
  tomcat:
    basedir: logs

db:
  num: 1
  user: ${MYSQL_USER:root}
  password: ${MYSQL_PWD:123456}
  url:
    0: jdbc:mysql://${MYSQL_HOST:twelvet-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:twelvet_nacos}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true

nacos:
  core:
    auth:
      plugin.nacos.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789
      enabled: false
      system.type: nacos
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

spring:
  datasource:
    platform: mysql  #这个过期属性不能修改，nacos 代码对此有硬编码
  security:
    enabled: true
  boot:  # 接入 spring boot admin
    admin:
      client:
        url: http://twelvet-monitor:8100
        username: twelvet
        password: 123456
        instance:
          service-host-type: ip
  application:
    name: @project.artifactId@
  main:
    allow-circular-references: true

useAddressServer: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        enabled: false
      elastic:
        enabled: false
